services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
  app:
     image: drinktracker
     ports:
      - "8080:8080"
     depends_on:
      - postgres

# pgadmin-compose:
#   image: dpage/pgadmin4
#   environment:
#     PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
#     PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
#   ports:
#     - "16543:80"
#   depends_on:
#     - postgres
